[server]
port=3344
key=""
base_url="https://api.b3n.fun/v1"

[mysql]
user_name="yuhanyang"
password="Hanke-110"
address="127.0.0.1:3306"
db_name = "chatbox"
max_idle_conn=10
max_open_conn=100

[chat]
default_app_id=12 