[server]
port=8989
key="sk-mRPg1ANRkqBB3JAxEb3185899519477dB896B558203e6183"
base_url="https://api.b3n.fun/v1"

[mysql]
user_name="yuhanyang"
password=""
address="127.0.0.1:3306"
db_name = "chatbox"
max_idle_conn=10
max_open_conn=100