// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

import (
	"time"
)

const TableNameApp = "app"

// App mapped from table <app>
type App struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	ModelID         int64     `gorm:"column:model_id;not null;comment:模型id" json:"model_id"`                               // 模型id
	Name            string    `gorm:"column:name;not null;comment:应用名称" json:"name"`                                       // 应用名称
	Temperature     float64   `gorm:"column:temperature;not null;default:0.00;comment:temperature" json:"temperature"`     // temperature
	TopP            float64   `gorm:"column:top_p;not null;default:0.00;comment:top_p" json:"top_p"`                       // top_p
	MaxOutputTokens int32     `gorm:"column:max_output_tokens;not null;comment:最大输出token" json:"max_output_tokens"`        // 最大输出token
	CreatedBy       int64     `gorm:"column:created_by;not null;comment:创建者uid,0:未定义,1:system" json:"created_by"`          // 创建者uid,0:未定义,1:system
	Introduction    string    `gorm:"column:introduction;not null;comment:介绍" json:"introduction"`                         // 介绍
	Prologue        string    `gorm:"column:prologue;not null;comment:开场白" json:"prologue"`                                // 开场白
	Prompt          string    `gorm:"column:prompt;not null;comment:prompt" json:"prompt"`                                 // prompt
	IsPublic        int32     `gorm:"column:is_public;not null;comment:是否公开" json:"is_public"`                             // 是否公开
	ShowPrompt      int32     `gorm:"column:show_prompt;not null;comment:是否展示prompt" json:"show_prompt"`                   // 是否展示prompt
	Icon            string    `gorm:"column:icon;not null;comment:图标" json:"icon"`                                         // 图标
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
