// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/hankeyyh/chat-box-svr/model/table"
)

func newChatHistory(db *gorm.DB, opts ...gen.DOOption) chatHistory {
	_chatHistory := chatHistory{}

	_chatHistory.chatHistoryDo.UseDB(db, opts...)
	_chatHistory.chatHistoryDo.UseModel(&table.ChatHistory{})

	tableName := _chatHistory.chatHistoryDo.TableName()
	_chatHistory.ALL = field.NewAsterisk(tableName)
	_chatHistory.ID = field.NewInt64(tableName, "id")
	_chatHistory.ParentID = field.NewInt64(tableName, "parent_id")
	_chatHistory.UserID = field.NewInt64(tableName, "user_id")
	_chatHistory.SessionID = field.NewInt64(tableName, "session_id")
	_chatHistory.AppID = field.NewInt64(tableName, "app_id")
	_chatHistory.Sender = field.NewString(tableName, "sender")
	_chatHistory.ErrNo = field.NewInt32(tableName, "err_no")
	_chatHistory.Content = field.NewString(tableName, "content")
	_chatHistory.CreatedAt = field.NewTime(tableName, "created_at")

	_chatHistory.fillFieldMap()

	return _chatHistory
}

type chatHistory struct {
	chatHistoryDo chatHistoryDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键
	ParentID  field.Int64  // 父id
	UserID    field.Int64  // 用户id
	SessionID field.Int64  // 所属会话id
	AppID     field.Int64  // 应用id
	Sender    field.String // 发送者
	ErrNo     field.Int32  // 错误码
	Content   field.String // 内容
	CreatedAt field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (c chatHistory) Table(newTableName string) *chatHistory {
	c.chatHistoryDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chatHistory) As(alias string) *chatHistory {
	c.chatHistoryDo.DO = *(c.chatHistoryDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chatHistory) updateTableName(table string) *chatHistory {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.ParentID = field.NewInt64(table, "parent_id")
	c.UserID = field.NewInt64(table, "user_id")
	c.SessionID = field.NewInt64(table, "session_id")
	c.AppID = field.NewInt64(table, "app_id")
	c.Sender = field.NewString(table, "sender")
	c.ErrNo = field.NewInt32(table, "err_no")
	c.Content = field.NewString(table, "content")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *chatHistory) WithContext(ctx context.Context) *chatHistoryDo {
	return c.chatHistoryDo.WithContext(ctx)
}

func (c chatHistory) TableName() string { return c.chatHistoryDo.TableName() }

func (c chatHistory) Alias() string { return c.chatHistoryDo.Alias() }

func (c chatHistory) Columns(cols ...field.Expr) gen.Columns { return c.chatHistoryDo.Columns(cols...) }

func (c *chatHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chatHistory) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.ID
	c.fieldMap["parent_id"] = c.ParentID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["session_id"] = c.SessionID
	c.fieldMap["app_id"] = c.AppID
	c.fieldMap["sender"] = c.Sender
	c.fieldMap["err_no"] = c.ErrNo
	c.fieldMap["content"] = c.Content
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c chatHistory) clone(db *gorm.DB) chatHistory {
	c.chatHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chatHistory) replaceDB(db *gorm.DB) chatHistory {
	c.chatHistoryDo.ReplaceDB(db)
	return c
}

type chatHistoryDo struct{ gen.DO }

func (c chatHistoryDo) Debug() *chatHistoryDo {
	return c.withDO(c.DO.Debug())
}

func (c chatHistoryDo) WithContext(ctx context.Context) *chatHistoryDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chatHistoryDo) ReadDB() *chatHistoryDo {
	return c.Clauses(dbresolver.Read)
}

func (c chatHistoryDo) WriteDB() *chatHistoryDo {
	return c.Clauses(dbresolver.Write)
}

func (c chatHistoryDo) Session(config *gorm.Session) *chatHistoryDo {
	return c.withDO(c.DO.Session(config))
}

func (c chatHistoryDo) Clauses(conds ...clause.Expression) *chatHistoryDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chatHistoryDo) Returning(value interface{}, columns ...string) *chatHistoryDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chatHistoryDo) Not(conds ...gen.Condition) *chatHistoryDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chatHistoryDo) Or(conds ...gen.Condition) *chatHistoryDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chatHistoryDo) Select(conds ...field.Expr) *chatHistoryDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chatHistoryDo) Where(conds ...gen.Condition) *chatHistoryDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chatHistoryDo) Order(conds ...field.Expr) *chatHistoryDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chatHistoryDo) Distinct(cols ...field.Expr) *chatHistoryDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chatHistoryDo) Omit(cols ...field.Expr) *chatHistoryDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chatHistoryDo) Join(table schema.Tabler, on ...field.Expr) *chatHistoryDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chatHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *chatHistoryDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chatHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *chatHistoryDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chatHistoryDo) Group(cols ...field.Expr) *chatHistoryDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chatHistoryDo) Having(conds ...gen.Condition) *chatHistoryDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chatHistoryDo) Limit(limit int) *chatHistoryDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chatHistoryDo) Offset(offset int) *chatHistoryDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chatHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *chatHistoryDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chatHistoryDo) Unscoped() *chatHistoryDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chatHistoryDo) Create(values ...*table.ChatHistory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chatHistoryDo) CreateInBatches(values []*table.ChatHistory, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chatHistoryDo) Save(values ...*table.ChatHistory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chatHistoryDo) First() (*table.ChatHistory, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*table.ChatHistory), nil
	}
}

func (c chatHistoryDo) Take() (*table.ChatHistory, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*table.ChatHistory), nil
	}
}

func (c chatHistoryDo) Last() (*table.ChatHistory, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*table.ChatHistory), nil
	}
}

func (c chatHistoryDo) Find() ([]*table.ChatHistory, error) {
	result, err := c.DO.Find()
	return result.([]*table.ChatHistory), err
}

func (c chatHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*table.ChatHistory, err error) {
	buf := make([]*table.ChatHistory, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chatHistoryDo) FindInBatches(result *[]*table.ChatHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chatHistoryDo) Attrs(attrs ...field.AssignExpr) *chatHistoryDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chatHistoryDo) Assign(attrs ...field.AssignExpr) *chatHistoryDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chatHistoryDo) Joins(fields ...field.RelationField) *chatHistoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chatHistoryDo) Preload(fields ...field.RelationField) *chatHistoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chatHistoryDo) FirstOrInit() (*table.ChatHistory, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*table.ChatHistory), nil
	}
}

func (c chatHistoryDo) FirstOrCreate() (*table.ChatHistory, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*table.ChatHistory), nil
	}
}

func (c chatHistoryDo) FindByPage(offset int, limit int) (result []*table.ChatHistory, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chatHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chatHistoryDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chatHistoryDo) Delete(models ...*table.ChatHistory) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chatHistoryDo) withDO(do gen.Dao) *chatHistoryDo {
	c.DO = *do.(*gen.DO)
	return c
}
