// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/hankeyyh/chat-box-svr/model/table"
)

func newSessionV2(db *gorm.DB, opts ...gen.DOOption) sessionV2 {
	_sessionV2 := sessionV2{}

	_sessionV2.sessionV2Do.UseDB(db, opts...)
	_sessionV2.sessionV2Do.UseModel(&table.SessionV2{})

	tableName := _sessionV2.sessionV2Do.TableName()
	_sessionV2.ALL = field.NewAsterisk(tableName)
	_sessionV2.ID = field.NewUint64(tableName, "id")
	_sessionV2.UserID = field.NewUint64(tableName, "user_id")
	_sessionV2.AppID = field.NewUint64(tableName, "app_id")
	_sessionV2.Name = field.NewString(tableName, "name")
	_sessionV2.CreatedAt = field.NewTime(tableName, "created_at")
	_sessionV2.UpdatedAt = field.NewTime(tableName, "updated_at")

	_sessionV2.fillFieldMap()

	return _sessionV2
}

type sessionV2 struct {
	sessionV2Do sessionV2Do

	ALL       field.Asterisk
	ID        field.Uint64 // 主键
	UserID    field.Uint64 // 用户id
	AppID     field.Uint64 // 应用id
	Name      field.String // 名称
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (s sessionV2) Table(newTableName string) *sessionV2 {
	s.sessionV2Do.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sessionV2) As(alias string) *sessionV2 {
	s.sessionV2Do.DO = *(s.sessionV2Do.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sessionV2) updateTableName(table string) *sessionV2 {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.UserID = field.NewUint64(table, "user_id")
	s.AppID = field.NewUint64(table, "app_id")
	s.Name = field.NewString(table, "name")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *sessionV2) WithContext(ctx context.Context) *sessionV2Do {
	return s.sessionV2Do.WithContext(ctx)
}

func (s sessionV2) TableName() string { return s.sessionV2Do.TableName() }

func (s sessionV2) Alias() string { return s.sessionV2Do.Alias() }

func (s sessionV2) Columns(cols ...field.Expr) gen.Columns { return s.sessionV2Do.Columns(cols...) }

func (s *sessionV2) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sessionV2) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["app_id"] = s.AppID
	s.fieldMap["name"] = s.Name
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s sessionV2) clone(db *gorm.DB) sessionV2 {
	s.sessionV2Do.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sessionV2) replaceDB(db *gorm.DB) sessionV2 {
	s.sessionV2Do.ReplaceDB(db)
	return s
}

type sessionV2Do struct{ gen.DO }

func (s sessionV2Do) Debug() *sessionV2Do {
	return s.withDO(s.DO.Debug())
}

func (s sessionV2Do) WithContext(ctx context.Context) *sessionV2Do {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sessionV2Do) ReadDB() *sessionV2Do {
	return s.Clauses(dbresolver.Read)
}

func (s sessionV2Do) WriteDB() *sessionV2Do {
	return s.Clauses(dbresolver.Write)
}

func (s sessionV2Do) Session(config *gorm.Session) *sessionV2Do {
	return s.withDO(s.DO.Session(config))
}

func (s sessionV2Do) Clauses(conds ...clause.Expression) *sessionV2Do {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sessionV2Do) Returning(value interface{}, columns ...string) *sessionV2Do {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sessionV2Do) Not(conds ...gen.Condition) *sessionV2Do {
	return s.withDO(s.DO.Not(conds...))
}

func (s sessionV2Do) Or(conds ...gen.Condition) *sessionV2Do {
	return s.withDO(s.DO.Or(conds...))
}

func (s sessionV2Do) Select(conds ...field.Expr) *sessionV2Do {
	return s.withDO(s.DO.Select(conds...))
}

func (s sessionV2Do) Where(conds ...gen.Condition) *sessionV2Do {
	return s.withDO(s.DO.Where(conds...))
}

func (s sessionV2Do) Order(conds ...field.Expr) *sessionV2Do {
	return s.withDO(s.DO.Order(conds...))
}

func (s sessionV2Do) Distinct(cols ...field.Expr) *sessionV2Do {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sessionV2Do) Omit(cols ...field.Expr) *sessionV2Do {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sessionV2Do) Join(table schema.Tabler, on ...field.Expr) *sessionV2Do {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sessionV2Do) LeftJoin(table schema.Tabler, on ...field.Expr) *sessionV2Do {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sessionV2Do) RightJoin(table schema.Tabler, on ...field.Expr) *sessionV2Do {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sessionV2Do) Group(cols ...field.Expr) *sessionV2Do {
	return s.withDO(s.DO.Group(cols...))
}

func (s sessionV2Do) Having(conds ...gen.Condition) *sessionV2Do {
	return s.withDO(s.DO.Having(conds...))
}

func (s sessionV2Do) Limit(limit int) *sessionV2Do {
	return s.withDO(s.DO.Limit(limit))
}

func (s sessionV2Do) Offset(offset int) *sessionV2Do {
	return s.withDO(s.DO.Offset(offset))
}

func (s sessionV2Do) Scopes(funcs ...func(gen.Dao) gen.Dao) *sessionV2Do {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sessionV2Do) Unscoped() *sessionV2Do {
	return s.withDO(s.DO.Unscoped())
}

func (s sessionV2Do) Create(values ...*table.SessionV2) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sessionV2Do) CreateInBatches(values []*table.SessionV2, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sessionV2Do) Save(values ...*table.SessionV2) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sessionV2Do) First() (*table.SessionV2, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*table.SessionV2), nil
	}
}

func (s sessionV2Do) Take() (*table.SessionV2, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*table.SessionV2), nil
	}
}

func (s sessionV2Do) Last() (*table.SessionV2, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*table.SessionV2), nil
	}
}

func (s sessionV2Do) Find() ([]*table.SessionV2, error) {
	result, err := s.DO.Find()
	return result.([]*table.SessionV2), err
}

func (s sessionV2Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*table.SessionV2, err error) {
	buf := make([]*table.SessionV2, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sessionV2Do) FindInBatches(result *[]*table.SessionV2, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sessionV2Do) Attrs(attrs ...field.AssignExpr) *sessionV2Do {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sessionV2Do) Assign(attrs ...field.AssignExpr) *sessionV2Do {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sessionV2Do) Joins(fields ...field.RelationField) *sessionV2Do {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sessionV2Do) Preload(fields ...field.RelationField) *sessionV2Do {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sessionV2Do) FirstOrInit() (*table.SessionV2, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*table.SessionV2), nil
	}
}

func (s sessionV2Do) FirstOrCreate() (*table.SessionV2, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*table.SessionV2), nil
	}
}

func (s sessionV2Do) FindByPage(offset int, limit int) (result []*table.SessionV2, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sessionV2Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sessionV2Do) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sessionV2Do) Delete(models ...*table.SessionV2) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sessionV2Do) withDO(do gen.Dao) *sessionV2Do {
	s.DO = *do.(*gen.DO)
	return s
}
